config/routes.rb
Examples::Application.routes.draw do

  match "/bad_calculate" => "BadCalculations#calculate"
  match "/calculate" => "Calculations#calculate"
  match "/calculate_better" => "Calculations#calculate_better"
  
  

  resources :calculations, :bad_calculations
  resources :clocks

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)
  
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

end

app/models/calculation.rb
class Calculation
  
  # not an active record model

  def initialize(a=0, b=0)
    @a = a
    @b = b
  end

  def add
    @a + @b
  end

  def subtract
    @a - @b
  end

  def multiply
    @a * @b
  end

end

app/models/calculator.rb
class Calculator
  class << self
    
    def add(a, b)
      a + b
    end

    def subtract(a, b)
      a - b
    end

    def multiply(a, b)
      a * b
    end

  end
end

app/models/clock.rb
class Clock < ActiveRecord::Base
  attr_accessible :minutes_ahead, :name
end

app/models/operand.rb
class Operand
  attr_reader :val

  def initialize(val=0)
    @val = val
  end

  def operate(a, op_id)
    case op_id
    when '1'
      add(a)
    when '2'
      subtract(a)
    when '3'
      multiply(a)
    end
  end

  def add(a)
    Calculator.add(@val, a.val)
  end

  def subtract(a)
    Calculator.subtract(@val, a.val)
  end

  def multiply(a)
    Calculator.multiply(@val, a.val)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bad_calculations_controller.rb
class BadCalculationsController < ApplicationController

  #all logic  in ctrlr
  def index
  end

  def calculate
    op = params[:op_id]
    a = params[:a].to_f
    b = params[:b].to_f

    case op
    when '1'
      @result = a + b
    when '2'
      @result = a - b
    when '3'
      @result = a * b 
    when '4'
      @result = a + 2*b 
    else 
      @result = a + b
    end
  end


end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController

  def index
  end

  def calculate
    op = params[:op_id]
    a = params[:a].to_f
    b = params[:b].to_f
    calc = Calculation.new(a, b)

    case op
    when '1'
      @result = calc.add
    when '2'
      @result = calc.subtract
    when '3'
      @result = calc.multiply
    else 
      @result = calc.add
    end
  end

  #skinny
  def calculate_better
    op = params[:op_id]
    a = Operand.new(params[:a].to_f)
    b = Operand.new(params[:b].to_f)
    @result = a.operate(b, op)
    @result = 0 if @result.nil?
  end

end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController


	respond_to :html, :js, :json, :xml
	def new
		@clock = Clock.new
   		respond_to do |format|
      		format.html # new.html.erb
      		format.xml  { render :xml => @clock }
    	end
	end

	def create
		 @clocknew = Clock.create(params[:clock])
    	@clocknew.save
    	@clock = Clock.all
    	render :action => 'index'
	end

	def index
		@clock = Clock.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clock }
    end
	end

	def show
		@clock = Clock.find(params[:id])
	end

	 def destroy
    @clock = Clock.find(params[:id])
    @clock.destroy

    respond_to do |format|
      format.html { redirect_to(clocks_path) }
      format.xml  { head :ok }
    end
  end

  def edit
     @clock = Clock.find(params[:id])
  end

  def update
     @clock = Clock.find(params[:id])

    respond_to do |format|
      if @clock.update_attributes(params[:clock])
        format.html { redirect_to(@clock, :notice => 'clock was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @clock.errors, :status => :unprocessable_entity }
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clock_helper.rb
module ClockHelper
end

app/views/bad_calculations/_smileys.html.erb
<div class="smiley_block">
  <% @result.to_i.times do%>
    <span><%= image_tag "smiley.png" %></span>
  <% end %>
</div>

app/views/bad_calculations/calculate.html.erb
<div class="calc_result">
  <h1> The result is : <span><%= @result %></span></h1>
  <%= link_to  calculations_path do %>
    <button><%= "&larr; Calculate Again".html_safe %></button>
  <% end %>
</div>


<% if @result > 0 %>
<div class="smiley_block">
  <% @result.to_i.times do%>
    <span><%= image_tag "smiley.png" %></span>
  <% end %>
</div>









<!--<%= render "smileys" %> -->
<% end %>

app/views/bad_calculations/index.html.erb
<div class="calc_form">
<h1> Calculator for 2 integers </h1>
<h3>Well, it can add, subtract and multiply!</h3>

<%= form_tag("/bad_calculate", :method => "post") do %>
  <%= text_field_tag(:a) %> &nbsp;
  <%= select_tag(:op_id, options_for_select([[' + ', '1'], [' - ', '2'], [' x ', '3']]) ) %>
  <%= text_field_tag(:b) %>
  <%= submit_tag("Calculate") %>
<% end %>
</div>

app/views/calculations/_smileys.html.erb
<div class="smiley_block">
  <% @result.to_i.times do%>
    <span><%= image_tag "smiley.png" %></span>
  <% end %>
</div>

app/views/calculations/calculate.html.erb
<div class="calc_result">
  <h1> The result is : <span><%= @result %></span></h1>
  <%= link_to  calculations_path do %>
    <button><%= "&larr; Calculate Again".html_safe %></button>
  <% end %>
</div>


<% if @result > 0 %>
<div class="smiley_block">
  <% @result.to_i.times do%>
    <span><%= image_tag "smiley.png" %></span>
  <% end %>
</div>









<!--<%= render "smileys" %> -->
<% end %>

app/views/calculations/calculate_better.html.erb
<div class="calc_result">
  <h1> The result is : <span><%= @result %></span></h1>
  <%= link_to  calculations_path do %>
    <button><%= "&larr; Calculate Again".html_safe %></button>
  <% end %>
</div>


<% if (@result > 1) %>
<div class="smiley_block">
  <% @result.to_i.times do%>
    <span><%= image_tag "smiley.png" %></span>
  <% end %>
</div>









<!--<%= render "smileys" %> -->
<% end %>

app/views/calculations/index.html.erb
<div class="calc_form">
<h1> Calculator for 2 integers </h1>
<h3>Well, it can add, subtract and multiply!</h3>

<%= form_tag("/calculate", :method => "post") do %>
  <%= text_field_tag(:a) %> &nbsp;
  <%= select_tag(:op_id, options_for_select([[' + ', '1'], [' - ', '2'], [' x ', '3']]) ) %>
  <%= text_field_tag(:b) %>
  <%= submit_tag("Calculate") %>
<% end %>
</div>

app/views/clocks/edit.html.erb
<%= form_for @clock do |f| %>
<div >
	<span><%= f.label :name %></span>  
  	<span><%= f.text_field :name %></span>
 </div>
 <div >
	<span><%= f.label :minutes_ahead %></span>  
  	<span><%= f.text_field :minutes_ahead %></span>
 </div>
 <div class="actions"><%= f.submit "submit" %></div>
  </div>
<% end %>
<div>
	<%= link_to 'Back To List', clocks_path %>
</div>

app/views/clocks/index.html.erb
<div>
	<p> The list of all clocks</p>
	<table>
	<% @clock.each do |c| %>
	<tr><td>
	  <%= link_to c.name, clock_path(c) %></td>
	   <td><%= link_to 'Edit', edit_clock_path(c) %></td>
	  <td><%= link_to 'Destroy', c, :confirm => 'Are you sure?', :method => :delete %></td>
	 </tr>
	<% end %>
</table>
</div>

<div>
	<span> Create a new clock </span>
	<%= link_to 'New Clock', new_clock_path %>

</div>

app/views/clocks/new.html.erb
<%= form_for @clock do |f| %>
<div >
	<span><%= f.label :name %></span>  
  	<span><%= f.text_field :name %></span>
 </div>
 <div >
	<span><%= f.label :minutes_ahead %></span>  
  	<span><%= f.text_field :minutes_ahead %></span>
 </div>
 <div class="actions"><%= f.submit "submit" %></div>
  </div>
<% end %>
<div>
	<%= link_to 'Back To List', clocks_path %>
</div>

app/views/clocks/show.html.erb
<%= javascript_include_tag "raphael-min" %>
<%= javascript_include_tag "clock" %>

<html>
<body>
<p> The created clock is : </p>
<input type="hidden" id="myval" value= <%= @clock.minutes_ahead %> /> 
<%= @clock.name %>
<%= @clock.minutes_ahead %>

<div>
<table border="1">
	
  <tr> <div id="clock_id" style="display:inline-block;"></div></tr>
  <tr> <div style="padding: 0px 20px;"><h2> <span id="digi_clock"></span></h2></div></tr>
 
  </table>
</div>
<div>
	<%= link_to 'Back To List', clocks_path %>
</div>
<body>
<html>

<script type="text/javascript">
var num=document.getElementById('myval').value;
 var num1 = parseInt(num);
  draw_clock(0,0+num1,0);
  draw_clock(0,0,0);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Examples</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>